FROM node:20-alpine as base

WORKDIR /usr/src/bd-airbnb

COPY package*.json ./

RUN npm install

COPY /. ./

FROM base as development

WORKDIR /usr/src/bd-airbnb

RUN chown -R 1000:1000 /usr/src/bd-airbnb

EXPOSE 3000

CMD [ "npm", "run", "dev" ]
